/perception/object_recognition/tracking/multi_object_tracker:
  ros__parameters:
    bicycle_tracker: pedestrian_and_bicycle_tracker
    bus_tracker: multi_vehicle_tracker
    can_assign_matrix:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    car_tracker: multi_vehicle_tracker
    consider_odometry_uncertainty: false
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    diagnostics_error_delay: 1.0
    diagnostics_error_extrapolation: 1.0
    diagnostics_warn_delay: 0.5
    diagnostics_warn_extrapolation: 0.5
    ego_frame_id: base_link
    enable_delay_compensation: true
    enable_unknown_object_motion_output: false
    enable_unknown_object_velocity_estimation: true
    input/detection01/channel: lidar_centerpoint
    input/detection01/objects: /perception/object_recognition/detection/centerpoint/validation/objects
    input/detection02/channel: none
    input/detection02/objects: /perception/object_recognition/detection/centerpoint_short_range/objects
    input/detection03/channel: none
    input/detection03/objects: /perception/object_recognition/detection/clustering/camera_lidar_fusion/objects
    input/detection04/channel: none
    input/detection04/objects: /perception/object_recognition/detection/irregular_object/objects
    input/detection05/channel: detection_by_tracker
    input/detection05/objects: /perception/object_recognition/detection/detection_by_tracker/objects
    input/detection06/channel: none
    input/detection06/objects: /perception/object_recognition/detection/radar/far_objects
    input/detection07/channel: none
    input/detection07/objects: /perception/object_recognition/detection/camera_vru/objects
    input/detection08/channel: none
    input/detection08/objects: input/objects08
    input/detection09/channel: none
    input/detection09/objects: input/objects09
    input/detection10/channel: none
    input/detection10/objects: input/objects10
    input/detection11/channel: none
    input/detection11/objects: input/objects11
    input/detection12/channel: none
    input/detection12/objects: input/objects12
    input_channels:
      detection_by_tracker:
        flags:
          can_spawn_new_tracker: false
          can_trust_classification: false
          can_trust_existence_probability: false
          can_trust_extension: false
          can_trust_orientation: false
        optional:
          name: detection_by_tracker
          short_name: dbT
      lidar_centerpoint:
        flags:
          can_spawn_new_tracker: true
          can_trust_classification: true
          can_trust_existence_probability: true
          can_trust_extension: true
          can_trust_orientation: true
        optional:
          name: centerpoint
          short_name: Lcp
    max_area_matrix:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 12.1
    - 12.1
    - 36.0
    - 60.0
    - 60.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 36.0
    - 12.1
    - 36.0
    - 60.0
    - 60.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 60.0
    - 12.1
    - 36.0
    - 60.0
    - 60.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 60.0
    - 12.1
    - 36.0
    - 60.0
    - 60.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 2.5
    - 10000.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 2.5
    - 2.5
    - 2.5
    - 2.5
    - 10000.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 2.5
    - 2.5
    - 2.5
    - 2.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 10000.0
    - 2.0
    - 2.0
    - 2.0
    max_dist_matrix:
    - 4.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 4.0
    - 2.5
    - 5.0
    - 5.0
    - 5.0
    - 1.0
    - 1.0
    - 1.0
    - 4.0
    - 2.5
    - 5.0
    - 5.0
    - 5.0
    - 1.0
    - 1.0
    - 1.0
    - 4.0
    - 2.5
    - 5.0
    - 5.0
    - 5.0
    - 1.0
    - 1.0
    - 1.0
    - 4.0
    - 2.5
    - 5.0
    - 5.0
    - 5.0
    - 1.0
    - 1.0
    - 1.0
    - 3.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 3.0
    - 3.0
    - 2.0
    - 3.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 3.0
    - 3.0
    - 2.0
    - 2.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 3.0
    - 3.0
    - 2.0
    max_rad_matrix:
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 1.047
    - 1.047
    - 1.047
    - 1.047
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 1.047
    - 1.047
    - 1.047
    - 1.047
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 1.047
    - 1.047
    - 1.047
    - 1.047
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 1.047
    - 1.047
    - 1.047
    - 1.047
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    - 3.15
    min_area_matrix:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 3.6
    - 3.6
    - 6.0
    - 10.0
    - 10.0
    - 0.0
    - 0.0
    - 0.0
    - 6.0
    - 3.6
    - 6.0
    - 10.0
    - 10.0
    - 0.0
    - 0.0
    - 0.0
    - 10.0
    - 3.6
    - 6.0
    - 10.0
    - 10.0
    - 0.0
    - 0.0
    - 0.0
    - 10.0
    - 3.6
    - 6.0
    - 10.0
    - 10.0
    - 0.0
    - 0.0
    - 0.0
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 0.1
    - 0.1
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 0.1
    - 0.1
    - 0.001
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 0.1
    - 0.1
    min_iou_matrix:
    - 0.0001
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.2
    - 0.2
    - 0.2
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.2
    - 0.3
    - 0.3
    - 0.3
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.2
    - 0.3
    - 0.3
    - 0.3
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.2
    - 0.3
    - 0.3
    - 0.3
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - -1.0
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.0001
    min_known_object_removal_iou: 0.1
    min_unknown_object_removal_iou: 0.001
    motorcycle_tracker: pedestrian_and_bicycle_tracker
    pedestrian_tracker: pedestrian_and_bicycle_tracker
    pruning_distance_thresholds:
    - 9.0
    - 5.0
    - 9.0
    - 9.0
    - 9.0
    - 4.0
    - 3.0
    - 2.0
    pruning_generalized_iou_thresholds:
    - -0.3
    - -0.4
    - -0.6
    - -0.6
    - -0.6
    - -0.1
    - -0.1
    - -0.1
    pruning_moving_object_speed: 5.5
    pruning_static_iou_threshold: 0.0
    pruning_static_object_speed: 1.38
    publish_debug_markers: false
    publish_merged_objects: false
    publish_processing_time: true
    publish_processing_time_detail: false
    publish_rate: 10.0
    publish_tentative_objects: false
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    tracker_lifetime: 1.0
    trailer_tracker: multi_vehicle_tracker
    truck_tracker: multi_vehicle_tracker
    unknown_association_giou_threshold: -0.8
    use_sim_time: true
    world_frame_id: map

