/perception/object_recognition/prediction/map_based_prediction:
  ros__parameters:
    acceleration_exponential_half_life: 2.5
    check_lateral_acceleration_constraints: false
    crossing_intention_duration: 0.3
    crosswalk_with_signal:
      distance_set_for_no_intention_to_walk:
      - 1.0
      - 5.0
      threshold_velocity_assumed_as_stopping: 0.25
      timeout_set_for_no_intention_to_walk:
      - 1.0
      - 0.0
      use_crosswalk_signal: true
    delta_yaw_threshold_for_searching_lanelet: 0.785
    dist_threshold_for_searching_lanelet: 3.0
    history_time_length: 1.0
    lane_change_detection:
      consider_only_routable_neighbours: false
      lat_diff_distance:
        diff_dist_threshold_to_left_bound: 0.29
        diff_dist_threshold_to_right_bound: -0.29
        dist_ratio_threshold_to_left_bound: -0.5
        dist_ratio_threshold_to_right_bound: 0.5
      method: lat_diff_distance
      num_continuous_state_transition: 3
      time_to_change_lane:
        cutoff_freq_of_velocity_for_lane_change_detection: 0.1
        dist_threshold_for_lane_change_detection: 1.0
        time_threshold_for_lane_change_detection: 5.0
    lateral_control_time_horizon: 5.0
    max_crosswalk_user_delta_yaw_threshold_for_lanelet: 0.785
    max_crosswalk_user_on_road_distance: 2.0
    max_lateral_accel: 2.0
    min_acceleration_before_curve: -2.0
    min_crosswalk_user_velocity: 1.39
    min_velocity_for_map_based_prediction: 1.0
    no_crossing_intention_duration: 1.0
    object_buffer_time_length: 2.0
    prediction_sampling_delta_time: 0.5
    prediction_time_horizon:
      pedestrian: 10.0
      unknown: 10.0
      vehicle: 15.0
    prediction_time_horizon_rate_for_validate_shoulder_lane_length: 0.8
    processing_time_consecutive_excess_tolerance: 1.0
    processing_time_tolerance: 0.5
    publish_debug_markers: true
    publish_processing_time: true
    publish_processing_time_detail: true
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    reference_path_resolution: 0.5
    sigma_lateral_offset: 0.5
    sigma_yaw_angle_deg: 5.0
    speed_limit_multiplier: 1.5
    use_crosswalk_user_history:
      match_lost_and_appeared_users: false
      remember_lost_users: false
    use_sim_time: true
    use_vehicle_acceleration: false

